version: 0.1
phases:
  pre_build:
    commands:
      - npm install
      - npm test
phases:
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Hamid1.1.pdf
    - styles/main.css
    - images/*
    - dist/bundel.js
